# Generated by Django 5.0.14 on 2026-08-04 11:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("connections", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("extraction_config", models.JSONField(blank=True, default=dict)),
                ("destination_mapping", models.JSONField(blank=True, default=dict)),
                (
                    "schedule_cron",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_connection",
                    models.ForeignKey(
                        limit_choices_to={"kind": "destination"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pipelines_as_destination",
                        to="connections.connection",
                    ),
                ),
                (
                    "source_connection",
                    models.ForeignKey(
                        limit_choices_to={"kind": "source"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pipelines_as_source",
                        to="connections.connection",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
