# Generated by Django 5.0.14 on 2026-08-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="strict_mapping",
            field=models.BooleanField(default=False),
        ),
    ]
