# Generated by Django 5.2.17 on 2026-08-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipelines", "0002_pipeline_strict_mapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="processing_mode",
            field=models.CharField(
                choices=[
                    ("python", "Python (in-process mapper)"),
                    ("spark", "Spark (distributed transform)"),
                ],
                default="python",
                max_length=20,
            ),
        ),
    ]
