# Generated by Django 5.0.14 on 2026-08-04 11:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("execution", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawPayloadRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("storage_uri", models.CharField(max_length=1024)),
                (
                    "content_type",
                    models.CharField(default="application/json", max_length=100),
                ),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("checksum_sha256", models.CharField(max_length=64)),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        help_text="Order within the run, e.g. page number"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_payloads",
                        to="execution.pipelinerun",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
        migrations.AddConstraint(
            model_name="rawpayloadrecord",
            constraint=models.UniqueConstraint(
                fields=("run", "sequence"), name="unique_raw_payload_sequence_per_run"
            ),
        ),
    ]
