# Generated by Django 5.0.14 on 2026-08-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rawstore", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawpayloadrecord",
            name="cursor_used",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="rawpayloadrecord",
            name="http_status",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rawpayloadrecord",
            name="item_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rawpayloadrecord",
            name="next_cursor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="rawpayloadrecord",
            name="source_path",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
