# Generated by Django 5.0.14 on 2026-08-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0002_pipelinerun_attempt_pipelinerun_celery_task_id_and_more"),
        ("rawstore", "0002_rawpayloadrecord_cursor_used_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rawpayloadrecord",
            options={"ordering": ["sequence", "created_at"]},
        ),
        migrations.RemoveConstraint(
            model_name="rawpayloadrecord",
            name="unique_raw_payload_sequence_per_run",
        ),
        migrations.AddField(
            model_name="rawpayloadrecord",
            name="loaded_successfully",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="rawpayloadrecord",
            constraint=models.UniqueConstraint(
                fields=("run", "sequence", "checksum_sha256"),
                name="unique_raw_payload_version_per_run",
            ),
        ),
    ]
