# Generated by Django 5.2.17 on 2026-08-14 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pipelines", "0003_pipeline_processing_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="SparkTransformConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("column_mappings", models.JSONField(blank=True, default=dict)),
                (
                    "pipeline",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spark_transform_config",
                        to="pipelines.pipeline",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
