# Generated by Django 5.0.14 on 2026-08-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("execution", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinerun",
            name="attempt",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of claim attempts made (Celery tries + retries).",
            ),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="celery_task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="error_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="error_is_retryable",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="last_successful_cursor",
            field=models.CharField(
                blank=True,
                help_text="Cursor of the last page fully extracted, stored, and loaded.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="pages_extracted",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="raw_payload_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="records_extracted",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="records_loaded",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="taskexecution",
            name="step",
            field=models.CharField(
                choices=[("extract", "Extract"), ("load", "Load"), ("run", "Run")],
                max_length=20,
            ),
        ),
    ]
