# Generated by Django 5.2.17 on 2026-08-04 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0002_pipelinerun_attempt_pipelinerun_celery_task_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinerun",
            name="continued_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this run was explicitly dispatched to continue a prior run that failed with PageLimitExceededError -- see apps.execution.dispatch.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="continuations",
                to="execution.pipelinerun",
            ),
        ),
    ]
