# Generated by Django 5.2.17 on 2026-08-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0003_pipelinerun_continued_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinerun",
            name="phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extracting", "Extracting"),
                    ("transforming", "Transforming"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="records_failed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="spark_job_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="spark_job_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
