# Generated by Django 5.2.17 on 2026-08-04 20:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orgs", "0002_organization_tenant_uuid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RawPayloadMigrationJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dry_run", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("partially_failed", "Partially failed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cancel_requested", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("records_inspected", models.PositiveIntegerField(default=0)),
                ("already_migrated", models.PositiveIntegerField(default=0)),
                ("legacy_unprefixed", models.PositiveIntegerField(default=0)),
                ("schema_prefixed", models.PositiveIntegerField(default=0)),
                ("missing_objects", models.PositiveIntegerField(default=0)),
                ("checksum_conflicts", models.PositiveIntegerField(default=0)),
                ("ready_for_migration", models.PositiveIntegerField(default=0)),
                ("records_migrated", models.PositiveIntegerField(default=0)),
                ("records_skipped", models.PositiveIntegerField(default=0)),
                ("sample_problem_records", models.JSONField(blank=True, default=list)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null if the initiating user was later deleted.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_payload_migration_jobs",
                        to="orgs.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["pending", "running"])),
                        fields=("organization",),
                        name="one_active_raw_payload_migration_job_per_org",
                    )
                ],
            },
        ),
    ]
